import img1 from "../image/Container.png"
import img2 from "../image/course.png"

const data = [
    {
        id: 0,
        title: "Ilmu Pertanian dan Biosistem",
        subTitle: "10. Working with loops on Swift",
        lessons: 40,
        Image: img2,
        teacher: "Dr. Sari Widya",
        review: 4.8,
    },
    {
        id: 1,
        title: "Teknologi Informasi dan Komputer",
        subTitle: "9. Functions and Closures",
        lessons: 35,
        Image: img1,
        teacher: "Prof. Ahmad Zain",
        review: 4.6,
    },
    {
        id: 2,
        title: "Teknik Sipil dan Lingkungan",
        subTitle: "8. Object-Oriented Programming",
        lessons: 50,
        Image: img2,
        teacher: "Ir. Budi Santoso",
        review: 4.9,
    },
    {
        id: 3,
        title: "Ilmu Komunikasi dan Media",
        subTitle: "7. Advanced UI with SwiftUI",
        lessons: 42,
        Image: img1,
        teacher: "Dr. Lestari Hapsari",
        review: 4.7,
    },
    {
        id: 4,
        title: "Pendidikan dan Keguruan",
        subTitle: "6. Working with JSON & API",
        lessons: 33,
        Image: img2,
        teacher: "M. Dimas Nugroho",
        review: 4.5,
    },
    {
        id: 5,
        title: "Ekonomi dan Manajemen",
        subTitle: "5. Navigation and Routing",
        lessons: 28,
        Image: img1,
        teacher: "Dr. Rina Dewi",
        review: 4.4,
    },
    {
        id: 6,
        title: "Ilmu Hukum dan Politik",
        subTitle: "4. Layouts in Swift",
        lessons: 22,
        Image: img1,
        teacher: "Prof. Andi Prasetyo",
        review: 4.3,
    },
    {
        id: 7,
        title: "Psikologi dan Sosial",
        subTitle: "3. Swift Basics",
        lessons: 18,
        Image: img2,
        teacher: "Dr. Maya Kusuma",
        review: 4.6,
    },
    {
        id: 8,
        title: "Kesehatan dan Kedokteran",
        subTitle: "2. Xcode Setup & Project Init",
        lessons: 14,
        Image: img2,
        teacher: "Dr. Aditya Ramlan",
        review: 4.5,
    },
    {
        id: 9,
        title: "Seni dan Desain",
        subTitle: "1. Introduction to iOS Dev",
        lessons: 10,
        Image: img1,
        teacher: "M. Rika Ayu",
        review: 4.2,
    },
];

export default data;
